version: "3"

services:
  app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env.docker
    command: pipenv run gunicorn -w 1 -b 0.0.0.0:5000 {{ cookiecutter.project_slug }}.app:create_app() --log-level debug

  db:
    image: postgres:12
    ports:
      - "5432:5432"
    volumes:
      - ~/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
